### ISSUE TITLE
Test using frame-streams on multiplexed streams

### ISSUE THREAD

**Issue by davedoesdev** [davedoesdev/bpmux#2]
@OEvgeny mentioned on #1 that it may not be working, so add a test for it.

**Comment by OEvgeny** [comment]
I was wrong. Got it to work properly. Adding test is always a good idea though!

**Comment by davedoesdev** [comment]
No problem - I agree adding a test is a good idea.
Thanks for letting me know.

**Comment by davedoesdev** [comment]
Added test in 9b8db84

**Comment by davedoesdev** [comment]
Btw, @OEvgeny if you're using TCP, I discovered that disabling Nagle (`setNoDelay`) can boost performance.

**Comment by OEvgeny** [comment]
That's good to know. Thanks!
