### ISSUE TITLE
general question

### ISSUE THREAD

**Issue by fas3r** [davedoesdev/bpmux#4]
Hello, 

I use the following [package](https://github.com/mmalecki/json-stream) to stream json data over tls connections from/to a client /server over a tls connection. 

It's using JSONStream as a parser/streamer and wait for the response using Promises after the request was sent. 

It's doing the work but looking at your repo I was wondering if I could not handle that directly using duplex streams. 

I'm just not sure how to implement it, is it like the "ping/pong" test ? As I'm using TLS socket,is it fine too as long as I provide a stream ?  

Thanks by advance.

**Comment by davedoesdev** [comment]
Hi @fas3r 
bpmux can multiplex multiple JSONStreams. What do you mean by handling it directly?
Thanks
David

**Comment by davedoesdev** [comment]
@fas3r I need a bit more detail on what you're doing

**Comment by fas3r** [comment]
Hello @davedoesdev ,

Sorry for the late reply. I would like to make some kind of proxy but instead of using http / https request  in a backend ( with `request` or `axios` for example ), I would like to use streams over tls. 

using express for example : 

```
const express = require('express')
const app = express()
const port = 3000

const serverB = require('../myTCPClient').TLS

app.get('/myTarget', (req, res) => 
  /* here I do some transformation. Let say "data" is an object of "data" /*
   const data = { ... }
 
  /* Then I would "transform" data as a "stream" using "JSONStreams" for example.
   const streamData = new JSONStreams(data) 
   
  /* Then I would send the data to "serverB" and wait for it answer, and reply with the data return from serverB */

   streamData.pipe(serverB).pipe(res)
   
)

app.listen(port, () => console.log(`Example app listening on port ${port}!`))
```

So the `client` do a API call type "get" to "/myTarget" request with some "queryArguments" ( for example ). 

When the request hit `server A`, a new request is send to `server B` and wait for the callback from `server B`, before sending the result to the client. 

The connection from server A to server B is  in reality a "pool" of  TLS connection already authenticated.

I basically would like to redo something like [this tls-json](https://github.com/timetocode/tls-json#readme) but using streams and bpmux. 

Thanks.

**Comment by davedoesdev** [comment]
@fas3r thanks. Yes, you could use bpmux for this scenario. It'll give you backpressure but at the price of some overhead.
Other options would be to queue your messages, or maybe tag requests and responses although then you're getting into how bpmux works anyway.

**Comment by davedoesdev** [comment]
@fas3r how did it go?

**Comment by fas3r** [comment]
Hello @davedoesdev, 

Sorry I did not see that the issue was still open. 

I did not have time to give a try  and I continue to use [tls-json](https://github.com/timetocode/tls-json#readme) for now.

I will close the issue that it does not remain open.

Thanks for the follow up.
